### ISSUE TITLE
Instant crash on Lineage 13

### ISSUE THREAD

**Issue by phuyuk** [39aldo39/DecSyncCC#1]
Install, launch, grant 3 permissions, "Unfortunately, DecSync CC has stopped"
Lineage 13, SM-P900 tablet

**Comment by 39aldo39** [comment]
Thanks for the report. It should be fixed now.

**Comment by chpio** [comment]
at least it hasn't deleted all your contacts, like it did for me, lineage 15.1

**Comment by 39aldo39** [comment]
I'm sorry to hear that. But I can't imagine that it is a bug in DecSync CC, it doesn't even touch other contacts. Maybe it is similar to https://gitlab.com/spacecowboy/Feeder/issues/138, where the same happens but with an app which can't read the contacts?
