### ISSUE TITLE
SD Card Support

### ISSUE THREAD

**Issue by tokenmath** [39aldo39/DecSyncCC#11]
Support for saving and changing files on the sdcard. Even changing the data directory in the app can not save or change data

**Comment by 39aldo39** [comment]
I think newer Android versions give limited access to the SD card. There is a new way to access the files, but DecSync currently has no support for it.

**Comment by tokenmath** [comment]
@39aldo39 Will it be supported for this?

**Comment by 39aldo39** [comment]
It won't be supported for the time being. I don't have a lot of time right now to work on it, and this isn't high on the list.

But if someone knows an easy way to add SD card support, I will look at it.

**Comment by moritztk** [comment]
Hi Aldo, are there any news to this?

**Comment by 39aldo39** [comment]
I have experimented what with the Storage Access Framework, which is the new way of accessing files. It does work and will try adding it. This should add SD card access as well!
