### ISSUE TITLE
Contact Syncing was off by default (had to turn on manually)

### ISSUE THREAD

**Issue by JacobRoth** [39aldo39/DecSyncCC#13]
Hi, this is a great little app but I noticed that after creating a new Address book under "Address books" in the DecSyncCC app, and adding contacts to that new address book, they wouldn't sync properly with my computer (Evolution-DecSync plugin). 

Turns out I had to go into the settings under "Users & accounts" to the "DecSync Contacts" item that had been created there and turn on sync manually. This is on Android 8.1.0 with no Google Apps.

is this intended behavior or a bug?

**Comment by empirefox** [comment]
Finally i found usage here.

**Comment by 39aldo39** [comment]
It is a bug. It should be enabled by default, but it turns off when the address book is renamed.

It should be fixed now. Do you known whether you renamed the address book at some point?
