### ISSUE TITLE
Does not write to file

### ISSUE THREAD

**Issue by moritztk** [39aldo39/DecSyncCC#14]
Hi, everytime I add a contact or an event in Android, it does not get written to file (and therefore not synced). 
If I hide and show a contact book / calendar in the DecSync app, the contacts/events I added via Android disappear, only the ones synced from laptop stay.

I am running the newest LineageOS, and installed from fdroid.

**Comment by 39aldo39** [comment]
Could you check the following:
* What does the entries count say? You can view it for every collection by pressing the three dots and then 'Entries count'.
* Is syncing enabled? See Settings → Accounts → DecSync Calendars / DecSync Contacts. What was the last sync time?

**Comment by moritztk** [comment]
It started working, I guess I needed to let it take some time. Thank you!
