### ISSUE TITLE
Choose root folder

### ISSUE THREAD

**Issue by essembeh** [39aldo39/DecSyncCC#2]
Hello

First, so much thanks for this app, this is an app I was waiting for so long :)

I couldn't find a way to configure the root folder, ie where files are stored (default is `~/DecSync`)
The idea would be to use a folder I already sync with syncthing, not to create a new shared one.

Thanks

**Comment by 39aldo39** [comment]
It is currently not possible to configure the root folder. It is indeed a nice feature, I will look at it sometime. I think it is also better if you can directly choose a Syncthing folder, with something like https://github.com/syncthing/syncthing-android/issues/1240, when it is implemented.

**Comment by 39aldo39** [comment]
I have now added the possibility to choose the DecSync directory in the settings.
