### ISSUE TITLE
FC on Android 10

### ISSUE THREAD

**Issue by ivysrono** [39aldo39/DecSyncCC#20]
1.1.8 and 1.1.9
[Havoc-OS-v3.0-20191031-oneplus3-Official.zip](https://sourceforge.net/projects/havoc-os/files/oneplus3/Havoc-OS-v3.0-20191031-oneplus3-Official.zip/download)
FC after give any permission.

**Comment by 39aldo39** [comment]
What do you mean by FC, a forced crash? Also, how did you install DecSync CC? 1.1.9 was not yet on f-droid when you created this issue and there is no APK for 1.1.8.

**Comment by ivysrono** [comment]
Yes, FC === a forced crash.
1.1.8 from F-Droid.
1.1.9 from github release

**Comment by ivysrono** [comment]
https://del.dog/ojatapicez

**Comment by 39aldo39** [comment]
Thanks for the stacktrace!

Could you check whether the directory `/storage/emulated/0/DecSync/` exists? My guess it that it does not. In that case the app is not allowed to write to the main storage, which is very strange as it allows for that permission. Do you know by change of any restrictions to the storage in Havoc OS?

**Comment by ivysrono** [comment]
Yes, dir `DecSync` do not exists.

**Comment by ivysrono** [comment]
I sync DecSync dir at first and try to reinstall app from f-droid.
FC only after I give it storage permission.
https://del.dog/uzacopuyir

**Comment by 39aldo39** [comment]
I was finally able to reproduce this issue.

The problem has to do with changed storage permissions in Android 10. However, the crash strangely does not occur when updating from an older version. As a workaround, you can first install version 1.1.4 from f-droid, and then update to 1.1.9. You can also wait for the next release.
