### ISSUE TITLE
Publish to Google Play Store

### ISSUE THREAD

**Issue by ghost** [39aldo39/DecSyncCC#21]
Hi,

Please publish this application to Google Play Store.

**Comment by mcladyz** [comment]
Hi,

Do you have any comment on this?

**Comment by 39aldo39** [comment]
I will publish at Google Play, but I have to do a few things before it. I will probably do it in the coming month.

**Comment by radasbona** [comment]
@mcladyz what is the problem with the f-droid store?

**Comment by mcladyz** [comment]
> @mcladyz what is the problem with the f-droid store?

- If you're running Android, it's an application you have to enable  `Install unknown apps`
- You will not get automatic updates (Automatic downloads only)
- Even on non-Android builds you will not get automatic updates. The flashable F-Droid package did originally enable this, but it stopped working at some point and IIRC, you now need Magisk to make it work.

In a nutshell: Lot's of security issues.

**Comment by mcladyz** [comment]
...and also lot's of people are never going to find this fine piece of software if it's only on F-Droid. Although there's a good probability that those people wouldn't even consider alternatives to Google etc. cloud sync and the like.

**Comment by 39aldo39** [comment]
I have finally added it to Google Play! I have made it paid, but it remains available on F-Droid for free.
