### ISSUE TITLE
Does not synchronize automatically?

### ISSUE THREAD

**Issue by Usodiariom** [39aldo39/DecSyncCC#24]
Hello, I love having my stuff with local copies, in open source and DecSync is perfect between Evolution in Linux and Android.

But I have the problem that doesn't sync to the Android calendar (Etar or Simple calendar)

I am using Syncthing.

When I create a new contact or calendar appointment:

From Android Calendar to Evolution linux (It works, synchronizes automatically)

From Evolution Linux to Android (does not automatically synchronize)
Files with Syncthing if synchronized
When I update the calendar manually it doesn't work.
When I update DecSync manually if I synchronize the calendar and contacts
But it doesn't do it automatically, it only works manually on android when it receives.

The calendar and DecSyn have all phone permissions, automatic started on startup, calendar and contact permissions, total battery usage and everything else

It can be fixed?

Thank you very much for the help.

**Comment by 39aldo39** [comment]
The Android app can only scan for new entries when the account is refreshed. You can see the last time it refreshed at Settings → Accounts → DecSync Calendars. It should refresh every hour automatically. Won't it do this, or would you like it to go faster?

**Comment by Usodiariom** [comment]
Hi, thanks for answering

I reinstalled the application, now I see that it does every hour and it is a pretty good time.

It would be good to know if the end user has access to modify the synchronization time.

Thank you very much for the software, I had a lot of time looking for a solution, I hope that one day it can be integrated into **gnome, kde and thunderbird**.

Among the solutions **to have everything local (outside the internet)** it complements very well with Syncthing since I am only interested in synchronizing my android phone with my laptop regardless of what network they are connected to, **regardless of IP changes.**


Open source solutions for productivity tools in the local environment

- Synchronize Files: **Syncthing**
- Synchronize Contacts: **DecSync CC**
- Synchronize Calendars: **DecSync CC**
- Synchronize Notes: **Many options**
- Synchronize notifications: **KDEConnect**
- Synchronize Web Bookmarks: **There is no known solution**


Greetings and thanks

**Comment by 39aldo39** [comment]
> It would be good to know if the end user has access to modify the synchronization time.

The end user doesn't have access to modify it, because it isn't necessary. An hour is the minimum allowed interval by Android, and increasing it isn't needed, as DecSync CC only syncs to the filesystem, which is very efficient, especially when there are no changes.
