### ISSUE TITLE
Thousands of "null,null" files in contacts folder

### ISSUE THREAD

**Issue by JohnVeness** [39aldo39/DecSyncCC#25]
I was looking in my DecSync/contacts folder and was surprised to see that it contains exactly 15000 files, especially given I only have 78 contacts. Looking in stored-entries there are two folders, one for each phone that used DecSyncCC, each about 3700 files in resources.

3620 of those files are exactly 34 bytes long and look like:

["2019-12-16T12:37:44",null,null]

The other 80 are sized a few hundred bytes each and look OK.

What's with all the 34-byte "null,null" files, and is there a proper way to clear them?

Many thanks for this app.

**Comment by 39aldo39** [comment]
Those "null,null" files are deleted contacts. It should only add those files when there is a contact you really remove. It is strange that you have 3700 of them with only 78 contacts. Do you remember deleting that many contacts?

Anyway, there is no proper way to clear them yet. As a workaround, you could export all your contacts, remove the corresponding DecSync subdirectory (first make a backup), and finally import your contacts fresh.

**Comment by JohnVeness** [comment]
Thanks for the reply. I don't think I've ever had that many "real" contacts, but my phone contacts list has had a long history, been passed from phone to phone and been hooked up to corporate systems which might have imported a load. I will try the export/import thing.

I expect this will solve another issue, which is that I have folders in my DecSync folders for phones that I no longer have. I was going to ask if there was an official way to clear out those folders (which again contain thousands of files), but I'm guessing just export, make new DecSync folder, import again?

**Comment by 39aldo39** [comment]
Yes, for now it is

**Comment by JohnVeness** [comment]
Sorry for very long delay, but finally got round to doing the export/import and it seemed to do the trick!
