### ISSUE TITLE
Support for older Android versions

### ISSUE THREAD

**Issue by tomasz1986** [39aldo39/DecSyncCC#29]
I am sorry if the issue tracker is not the right place to ask this question, but is there any chance to support older versions of Android than 4.4?

I am asking, because I have at least 2 devices, where the last official version of Android is 4.1. Does DecSync CC use any specific features that are only available in Android 4.4 and later?

**Comment by 39aldo39** [comment]
The [ical4android](https://gitlab.com/bitfireAT/ical4android) library that I use for handling the calendar data requires at least Android version 4.4. The most recent version even 5.0. The reality is that on Android a lot of stuff changes often, which makes it complicated to support very old versions. As few devices have a version < 4.4 (or even < 5.0) it is unfortunately just not worth the trouble to support them.
