### ISSUE TITLE
Option for choosing a color for a calendar

### ISSUE THREAD

**Issue by java-py-c-cpp-js** [39aldo39/DecSyncCC#3]
First things first: Thank you for this great app :-)

It would be great to have an option for choosing a color for the calendars so you can easily see which entry came from which calendar.

**Comment by 39aldo39** [comment]
You can change the color of calendars using other apps, for example [Calendar Color](https://f-droid.org/en/packages/ch.ihdg.calendarcolor/). DecSync CC will even notice the change and sync the color to other devices. But adding the possibility directly or linking to an app may be a good addition.

**Comment by java-py-c-cpp-js** [comment]
Thank you for your response. I managed to change the color with DecSync for Evolution at my own, but adding an option for that directly in the DectSyncCV app would be really great.

**Comment by phuyuk** [comment]
'Calendar Color' (F-Droid) is an excellent, simple utility for this. Color can be changed on a whim, immediately respected system-wide.

**Comment by 39aldo39** [comment]
I have added a link to Calendar Color in the app to make it more discoverable.
