### ISSUE TITLE
Events created/modifyied on tablet dont sync with evolution

### ISSUE THREAD

**Issue by mstyp** [39aldo39/DecSyncCC#34]
So my tablet (samsung galaxy tab A sm-t290 running android 9) is air-gapped and only connects via wifi to a local network of computers which also never touches the internet. **Please dont suggest a solution involving connecting the tablet or my home server to the wider internet**. This is both not possible, and not wanted. 

I installed decsync CC and Syncthing, and both work for syncing regular files. When I add an event in evolution, it shows up on my tablet after I uncheck and recheck the calander in DecSync CC. A bit annoying but whatever. 

The problem is that new events I make in my android calander dont sync to evolution. Any changes I make locally on my android tablet get reset after I uncheck and recheck the calander in DecSync CC.

I know that [davx5](https://www.davx5.com) relies on the android sync framework or whatever for syncing, and that that framework breaks without an internet connection. Is DecSyn CC similar? 

I am pretty sure the issue is with tablet and not with my server, as it can sync events just fine between my raspberry pi and my laptop.

Is there some setting I need to change in order to make DecSync CC share changes I make to events and new events sync with evolution?

**Comment by 39aldo39** [comment]
> I know that davx5 relies on the android sync framework or whatever for syncing, and that that framework breaks without an internet connection. Is DecSyn CC similar?

Yes, DecSync CC uses the same sync framework. I can confirm that it doesn't work if you don't have internet access at all. I will try to find a way around it, but it isn't that straightforward to fix.

**Comment by mstyp** [comment]
gah. It boggles my mind that android sync does not work without an internet connection. I wonder where the best place to issue a ticket to the android devs would be?

Are there any other calander syncing apps that *do* work with zero internet access? My tablet and my server are on the same network, it *should* be easy to do calander syncing.

**Comment by 39aldo39** [comment]
I added an option for the next version, which allows the app to sync regularly on its own, regardless of the sync adapter!

**Comment by mstyp** [comment]
> I added an option for the next version, which allows the app to sync regularly on its own, regardless of the sync adapter!

YESSSS thank you. ima send you $5 in btc.
