### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by JohnVeness** [39aldo39/DecSyncCC#37]
A dark mode would be lovely :)

**Comment by 39aldo39** [comment]
I looked at it, and it actually is very easy to implement nowadays! I expected it to be more work and didn't give it priority as you shouldn't be too much in the app. But I added it now as it wasn't that difficult!

**Comment by JohnVeness** [comment]
Many thanks. Yeah, I wasn't sure if it was worth asking because, as you say, the user doesn't actually see the app UI much. But I'm glad I did and I'm glad it wasn't too hard.
