### ISSUE TITLE
Entries count?

### ISSUE THREAD

**Issue by SmilingHorse** [39aldo39/DecSyncCC#4]
Calendar import/export has a text field that reports the number of events per calendar file.

Similarly, when you import/export contacts you can see the number of contacts being backed up.

It would be helpful, for debugging purposes, to have DecSyncCC report how many entries it has so you'd be able to tell if it picked up a newly created entry. Especially when people would notice it takes a while for entries to sync but won't be sure if it's Android not syncing fast enough, DecSyncCC not coming out off Battery Saving suspension to write the files, or Syncthing taking its sweet time to negotiate...

Anyhow, thanks for DecSyncCC! My uni's wifi firewall is blocking me from reaching to my OwnCloud service but Syncthing works fine so no more manual import/exports for me! :)

**Comment by 39aldo39** [comment]
I have added an entries count. It shows the number of entries on Android, the number of processed entries and the number of entries in DecSync. If you update from the old version, the processed entries won't show up until you disable and enable the collection.

Furthermore, when you enable a collection, a notification is shown while the initial sync happens.
