### ISSUE TITLE
Provide information on required Android versions

### ISSUE THREAD

**Issue by tomasz1986** [39aldo39/DecSyncCC#40]
DecSync CC 1.2.2 and older supports Android 4.4+, while DecSync CC 1.2.3+ supports Android 5.0+.

However, right now, this information is not provided anywhere explicitly. The only way to find the required Android version seems to be either going through the commit history and looking for the minimum supported SDK changes, or using the F-Droid application and checking the version history there. Even the F-Droid website lists only the last three versions, which is not very useful.

I think that it would be helpful to have this information included here on GitHub, either in the readme, or next to each release, especially when the Android version requirements have been increased.

**Comment by 39aldo39** [comment]
Thanks for the notice, it is indeed good to provide the info explicitly. I have added the info to the README and in releases that change the required version.
