### ISSUE TITLE
message "Adding events of <calendar name>" for hours

### ISSUE THREAD

**Issue by visir** [39aldo39/DecSyncCC#42]
I finally got it running so far that calendar entries are transferred from Evolution to Decsync CC on my Android phone (Entries count shows a reasonable number). Then above message appeared and I thought "nice - now I will see the entries soon". This was 12 hours ago, the message is still there and the "busy" line below is still running. 

The calendar is marked to be synchronized in the calendar app. 

Ah yes, and everytime I try to get DecSync CC to do anything, like synchronizing, the message (freely translated) "DecSync CC was stopped" or "...was repeatedly stopped" shows. But the app is still open... ?

Did I miss anything?

Best regards,
Wolfgang

**Comment by 39aldo39** [comment]
Thanks for the report! It shouldn't stay that long. That the message "DecSync CC was stopped" is shown while the app is still open indicates that the background process crashed. It would be very helpful if you could send the log using 'logcat'. It is a bit complicated to set up, but for some context you could look [here](https://github.com/39aldo39/DecSyncCC/issues/36#issuecomment-665835134).

Also it would you useful to know you Android and DecSync CC versions.

**Comment by visir** [comment]
That message is still there, continuously... and nothing showing up in the calendar. At least it doesn't seem to use much battery.
Where do I see the DecSync version? "About DecSync CC" brings me to the website...
Android is 7.1.2 "Fairphone OS" on a Fairphone 2.

Let's see when I find the time for logcat...

**Comment by 39aldo39** [comment]
You can check the DecSync CC version going its information screen inside Android (long press and select App-info). It is strange that the notification stays for you. In my testing it will disappear when the background process crashes...

Also, does it disappear when you de-select the collection?

**Comment by visir** [comment]
Well, the version is 1.3.0
de-selecting everything didn't remove the message, but now another collection appeared in the app... with a name without match on the computer... and now I have two messages! One with contacts, one with events, and the run time started new.
logcat sounds complicated...

**Comment by 39aldo39** [comment]
Version 1.3.0 is a very old version. The current one is 1.4.3, which includes significant changes regarding this. I suggest disabling the collections, uninstalling this version and then installing the latest version. Hopefully that works.

**Comment by visir** [comment]
I installed it first some weeks/ months ago, most likely from F-Droid. 1.3.0 was added there on July 18th. Since July 29th, 1.4.0 is available - I must have installed it in between. I try 1.4.0... by the way: is there no update process, avoiding uninstalling/ installing?

**Comment by visir** [comment]
...looked the site up in the browser and installed 1.4.3 from there - contacts are here again and the process finished, 
...calendar process finished, too, and events are there - seems to work now!
Thanks!

**Comment by 39aldo39** [comment]
> is there no update process, avoiding uninstalling/ installing?

Updating works just fine. But in your case I was a bit worried the notification may stay through the update, although it probably wouldn't.

Note that by installing the APK from GitHub, you have to get updates from there too. If you want to switch to the F-Droid version at some point, you do have to reinstall.
