### ISSUE TITLE
App force closes on launch after trying tasks

### ISSUE THREAD

**Issue by kannes** [39aldo39/DecSyncCC#44]
My decsync is broken D:
When I launch it, I briefly see a white screen, then it's gone and Android says the app was repeatedly closed.

I wanted to try the new tasks feature so I tried to add a task element called "decsync tasks". Nothing appeared below my calendar and contacts. Tried to add one called "tesz" (or something similar, I typoed). Nothing appeared. I decided it was a good moment to rename my address book "decsync" to "decsync addresses". Then went to settings to see if there was anything about tasks. I saw the tasks app setting and opened it. Saw opentasks and selected it. Then the app crashed (I think immediately, not sure though). Now it crashes every time I try to open it.

When this happened I had no lists in opentasks at all. I later tried to add one (local one) and a task to it. This did not stop DecSyncCC from crashing.

There is a directory `tasks` with two collection subdirectories in my DecSyncCC directory. 

DecSyncCC 1.5.0 from fdroid.

**Comment by 39aldo39** [comment]
Thanks for the report! It turns out that the problem had to do with the tasks permissions and is fixed in version 1.5.2. As a workaround, you can go to the app info of DecSync CC (in Android, not DecSync CC) → Permissions → Additional permissions → Tasks → Allow.

**Comment by kannes** [comment]
Cheers! I'll wait for it to appear in fdroid and report back.
