### ISSUE TITLE
Can't modify an event created in evolution 

### ISSUE THREAD

**Issue by l4nc3l0t** [39aldo39/DecSyncCC#48]
If I want to modify an event created or modified in evolution it's impossible to modify it in etar (default calendar) on lineageos. Only allowed to delete or share it. Don't know if it's a problem of evolution-decsync or decsynccc. Or maybe I'm doing something wrong.
Using evolution-decsync 1.3 with libdecsync 1.8.3 in evolution 3.38 on debian testing

**Comment by 39aldo39** [comment]
Thanks for the notice! It turns out that that it was a problem with the library I used (ical4android). Updating it fixed it.

It should be fixed in the next release.

**Comment by l4nc3l0t** [comment]
Perfect, thank you for this wonderful tool by the way
