### ISSUE TITLE
Choose color for task lists

### ISSUE THREAD

**Issue by abaker** [39aldo39/DecSyncCC#49]
Tasks.org allows users to change task list colors, but disables this functionality for OpenTask lists because it cannot modify the color in the content provider

This is similar to #3, but unfortunately can't be solved by a third party app

**Comment by 39aldo39** [comment]
Thanks for the notice! I didn't realize that tasks.org couldn't modify the color, so it looks like I have to add the functionality.

**Comment by abaker** [comment]
I just tested it out, thanks for the quick fix!
