### ISSUE TITLE
Thank You.

### ISSUE THREAD

**Issue by phuyuk** [39aldo39/DecSyncCC#5]
Very cool app. This is THE missing link for P2P sync.

Thank you very much for doing this.

**Comment by java-py-c-cpp-js** [comment]
I can confirm this issue ;-)

**Comment by ar-** [comment]
I also confirm this issue. I've been waiting for this app since years. I was about to make it by myself. Awesome!!!!

**Comment by 39aldo39** [comment]
Thank you for the kind words! I created because it was missing in P2P sync, glad more people like it.

**Comment by Catfriend1** [comment]
Yehaaaa! :-)

**Comment by konradmihelsson** [comment]
Thank you very much! Your app in F-Droid repo is cool!

**Comment by TheMatten** [comment]
+1 :D

**Comment by 39aldo39** [comment]
Thank you very much! I have added a Bitcoin address for donations (`1JWYoV2MZyu8LYYHCur9jUJgGqE98m566z`).

**Comment by zubkov-andrei** [comment]
This app is really needed! Thank you! Consider adding other ways for donation. I'm not using bitcoin, and I'm sure, not only I.

**Comment by phuyuk** [comment]
Same here. Paypal only.

**Comment by 39aldo39** [comment]
There is a PayPal option now

**Comment by leela52452** [comment]
@39aldo39 update something like this `paypal.me/usernane`, it will useful to.remember

**Comment by 39aldo39** [comment]
I think the current button is more appropriate, as there is also a goal (DecSync) attached to it. Nonetheless, `paypal.me/39aldo39` also exists now.
