### ISSUE TITLE
Can't set custom color to individual events

### ISSUE THREAD

**Issue by Elaborendum** [39aldo39/DecSyncCC#51]
When creating an event with Samsung calendar, strange things happen when trying to set a color other than the calendar's default:

- If the event is new and I try changing the color, the app discards the event because "no information was introduced". There are no problems if I leave the default one.
- If I try changing the color of any prexisting event, the app discards any changes made at the same time because "no information was introduced". Again, no problems if I leave the default one.

There are no problems if I use Etar Calendar, but I'd prefer to avoid having two calendar apps. Is this just a problem with the Samsung one?

**Comment by 39aldo39** [comment]
I suspect that it is a problem with the Samsung calendar, as it works fine in Etar and DecSync CC doesn't (and can't) differentiate between different apps. Unfortunately, I can also not really test it as I don't have a Samsung device.

But it does look like custom event colors have to be handled a bit special. Could you test whether it works in Davx⁵/Etesync, if that is a possibility?

**Comment by Elaborendum** [comment]
I've tested with Davx⁵ and there's not even an option to set a color. The option was there on Etar, but it got stuck loading and never showed any options. I thought it could be related to battery saving mode, but I also turned that off and the problem persisted on both.

On Samsung Calendar however, I can change an event to the default calendar color from whatever custom color I chose in Etar.

I don't have the Calendar Color app installed, if that is still required for something.

**Comment by 39aldo39** [comment]
I have found [this](https://www.davx5.com/faq/setting-event-colors-crash) for Davx⁵, so it looks like it doesn't work on the Samsung calendar. If you just don't want to have two calendar apps, maybe you could disable the Samsung one as a workaround, so it doesn't show up at all?

**Comment by Elaborendum** [comment]
Sure, I'll do that. Thanks.
