### ISSUE TITLE
Auto suggest a new name for a collection

### ISSUE THREAD

**Issue by JohnVeness** [39aldo39/DecSyncCC#54]
When the user clicks the + to create a new collection, the name is blank so they have to type in a new name from scratch. I think it would be good if there could be a pre-filled suggested collection name, e.g. DecSync, so the user could just click OK in many cases. Bonus points for detecting if there is already a collection of the same name, and offering, e.g. "DecSync 2" in that case.

**Comment by 39aldo39** [comment]
Thanks for the suggestion! I agree and have implemented it. I did use 'Personal' as a default name as that is more common I think.
