### ISSUE TITLE
Share (sync) only selected calendars with other people

### ISSUE THREAD

**Issue by ghost** [39aldo39/DecSyncCC#56]
I like to share only some selected calendars with other people. I am thinking about scenario similar to this:

- I create those directories: `sync-personal` and `sync-family`
- `sync-personal` is synced via Synthing with my notebook only (personal stuff)
- `sync-family` is synced via Synthing with my notebook **and with phones of other family members**
- I now create calendar "Family" with stuff I want to share with my family and save it into `sync-family`
- Now, I like to be able to allow all memebers of my family view/edit this calendar 

Is this currently possible? And if not, can this be somehow solved? 

Thank you. :)

**Comment by DefiCzech** [comment]
It would be amazing, have possibility to set different directories per calendar, task and contact. Or maybe calendars, task, contacts groups. Current solution **one sync directory for everything** is very limiting.

**Comment by Alch-Emi** [comment]
I'm also in this situation with my partner.  We both have networks of Syncthing devices, and want to share a few calendars and task lists, but each also have our own.  We've resorted to sharing individual task folders (e.g. `Decsync Root/tasks/<uuid>`) with Syncthing, but it gets very cumbersome very quickly.  An official solution would be amazing.

**Comment by aviladev** [comment]
I'm in the same situation. Although I didn't test myself, I think a possible workaround would be to setup a work profile on Android through the [Shelter](https://cgit.typeblog.net/Shelter/about/)  app, and install a secondary DecSync there. But then it would be a little inconvenient to also use a second Contacts, Calendar, Tasks and Syncthing apps...

**Comment by 39aldo39** [comment]
I have now added the possibility to add multiple DecSync directories for this purpose! It will be available in the next release.
