### ISSUE TITLE
Read bytes entries are not produced 

### ISSUE THREAD

**Issue by cinghiopinghio** [39aldo39/DecSyncCC#6]
The `read bytes` folders for calendars and contacts are not produced as described by the file `internals.md`.
Is this a design feature or are those files optional. 

I'm planning to write a port in python so a clear description of the algorithm would be great. 

Anyway, great idea. This was very much needed.

**Comment by cinghiopinghio** [comment]
I have only one device syncing to my desktop (which is just a "backup" since it doesn't read it).
The final folder tree is as follow:

``` bash
├── calendars
│   └── colID14241
│       ├── new-entries
│       │   └── VTR-L29-DecSyncCC
│       │       ├── .decsync-sequence
│       │       ├── info
│       │       └── resources
│       │           ├── d99be6c8-2924-4cf6-9fe5-0d313f8d2a58
│       │           └── .decsync-sequence
│       └── stored-entries
│           └── VTR-L29-DecSyncCC
│               ├── info
│               └── resources
│                   └── d99be6c8-2924-4cf6-9fe5-0d313f8d2a58
├── contacts
│   └── colID34234
│       ├── new-entries
│       │   └── VTR-L29-DecSyncCC
│       │       ├── .decsync-sequence
│       │       ├── info
│       │       └── resources
│       │           ├── 65c943d9-50cb-4a85-b9b0-2d20a3bf4b94
│       │           └── .decsync-sequence
│       └── stored-entries
│           └── VTR-L29-DecSyncCC
│               ├── info
│               └── resources
│                   └── 65c943d9-50cb-4a85-b9b0-2d20a3bf4b94
```

**Comment by 39aldo39** [comment]
If there is just one device syncing, there is indeed no `read-bytes` directory. Every device only reads the new entries of other devices, not of itself. Since there are no other devices, it doesn't create the directory.

**Comment by cinghiopinghio** [comment]
Thanks, that explains the lack of `read-bytes`.
