### ISSUE TITLE
Processed Entries vs DecSync Entries

### ISSUE THREAD

**Issue by MisterY** [39aldo39/DecSyncCC#76]
Hi!

Could someone explain the difference between Processed Entries and Android/DecSync Entries?

I've finally fixed the VCARD records so that my DecSync and Android numbers match. But I'm having trouble figuring out what the Processed Entries are. 
This number is higher than Android/DecSync numbers. Does this matter?

Cheers,

Alen

**Comment by MisterY** [comment]
I no longer see the "processed entries" line. Either this has changed in the later version or it disappeared after cleaning up the contacts list and fixing the records.

The difference in numbers came from collecting the contacts with multiple applications over the last 20 years.

**Comment by 39aldo39** [comment]
I agreed that the semantics of the processed entries aren't very clear or useful, so I removed them. The Android and DecSync counts are enough to see whether the syncing is working.
