### ISSUE TITLE
Noob question?

### ISSUE THREAD

**Issue by shadowbone94** [39aldo39/DecSyncCC#8]
Sorry because this is might not be an issue per se, but I'm having trouble understanding how this app works.

I made a new collection and a .mwbs file got created in the directory. But the entries count still shows 0.

So I'd like to ask:

1. How does this work? Like this simply backsup contacts locally to a file or something. If so, is it readable in any document readers ?

Because this file is just 41kb whereas the .vcf backup I usually take is about 250kb.

2. How can I restore the backed up file if I want to restore the contacts?

Thanks in advance.

**Comment by 39aldo39** [comment]
The app uses the directory to store the contacts. However, it doesn't use a single file, but a whole directory structure with multiple files in such a way that multiple apps can edit it at the same time without any conflicts. If you store just a single file, this is not possible.

When you create a new address book, there should be some directories created in `DecSync/contacts/colID12345` (with some arbitrary number), for example `new-entries` and `stored-entries`. The app doesn't create a `.mwbs` file. Maybe something else created it?

The files in the directory are not very useful for other apps, but that is not needed. When you create a new address book, you can store new contacts in it, or import old contacts using any contacts application. If you synchronize the DecSync directory with another device, it will synchronize the contacts stored in it when you tell it to. You can also backup the directory, in which case you can restore the contacts if you restore the files in it.

**Comment by shadowbone94** [comment]
@39aldo39 Thanks.

So just to see if I got it right.

DecsynCC does not automatically sync the contacts from the device (because I was under the impression it does), rather, we need to export contacts into it?

If so, could you please guide me how to go about doing this?

Also, in that case what woukd be the difference between this service and the usual exporting contacts as .vcf file from android contacts app?

**Comment by 39aldo39** [comment]
If you create a collection in DecSync CC, it creates a new address book in Android.  If you create a new contact you have the option to store it in this new address book. It doesn't moves existing contacts around. You can import a `.vcf` file using the default contacts application (in the settings).

The a advantage of this app is that new contacts and modified contacts are automatically stored, and that you can sync with other devices.

**Comment by shadowbone94** [comment]
@39aldo39 Thank you so much. Now that cleared things up.

Closing the thread. Thanks for your help.
