### ISSUE TITLE
Multiple Sync Folders?

### ISSUE THREAD

**Issue by KarlZeilhofer** [39aldo39/DecSyncCC#89]
Hi, 

I really like DecSync with Syncthing. 

I'd like to sync different phone books/calendars with different people. I can only set a single folder in DecSync. Is it possible, to set different folders for different phone books/calendars?

Greets, Karl

**Comment by 39aldo39** [comment]
It is possible to sync multiple folders, but in a slightly different way. If you press the button in the top left (or slide from the left), a menu appears with an 'Add directory' button. This allows you to add another folder!

**Comment by KarlZeilhofer** [comment]
Great, but why do you say it's different? It's exactly what i've been looking for.

**Comment by 39aldo39** [comment]
Yes, it is the same. The only difference I meant was that you get a separate list and that you cannot select a folder for existing collections.
