### ISSUE TITLE
Contacts are not syncing

### ISSUE THREAD

**Issue by regaldude** [39aldo39/DecSyncCC#92]
My contacts are not syncing properly through Decsync.

Last active dates that I see when inspecting the address book are couple months ago.
My entry counts are also very wrong and it lists 0 entries under Android.

I can provide more information regarding the issue if required.

I am also open to creating a new address book and moving my contacts there. Not sure what I have to do in order to achieve this.

**Comment by JackSlaterIV** [comment]
I have just installed this app from F-droid and I have the exact same issue.
Have you found any solution?

**Comment by regaldude** [comment]
For me, the issue was related to permissions. Android 13 periodically removes unused permissions and removed access to contacts.

**Comment by regaldude** [comment]
Closing this as my issue was related to permissions given to Decsync
