### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by JayXT** [39aldo39/DecSyncCC#93]
Does it receive vulnerability and bug fixes for example?

**Comment by 39aldo39** [comment]
Yes, I still maintain it. Lately, I did not make a lot of time for it, so no major improvement. But I also use it myself, so it continues to get vulnerability and bug fixes.

**Comment by JayXT** [comment]
Thank you for your work! It's a really crucial project that despite being simple, empowers users with tools to establish truly decentralized ecosystem. The solution really shows the power of a 'file' concept, which many nowadays neglect in favor of vague and internally complicated cloud solutions. At the same time separation of concerns like sync and data storage is another DecSync CC forte.

**Comment by onetimecontributor** [comment]
hi @39aldo39 , are you still using the app? if no, have you heard if anyone has picked it up in a reasonable manner?
